### Ping 
GET http://localhost:3000/api

### Users  
GET http://localhost:3000/api/users
Content-Type: application/json

{
  "token": "ed999c4e-4132-4114-84e5-b8bc1ef4add6"
}

### Register  
POST http://localhost:3000/api/users/
Content-Type: application/json

{
    "username": "Lala",
    "mail": "usuario1@example.com",
    "password": "otaku"
  }

### Login  
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
  "username": "Lala",
  "password": "otaku"
}